import pandas as pd

questions = pd.read_csv("QNA.csv")
correct_answer_list : list = []

for i in range(len(questions)):
    correct_answer_list.append(int(questions.loc[i, "Correct Answer"]))

sorted_questions : dict = {
    "Fun" : {
        "Easy" : (0, 11),
        "EasyText" : "Etes-vous prêt à connaitre la vérité sur Mathis ?",
        "Normal" : (0, 11),
        "NormalText" : "Etes-vous prêt à voir la face cachée de Mathis ?",
        "Hard" : (0, 11),
        "HardText" : "Etes-vous prêt à connaitre le vrai Mathis ?",
        "Lunatic" : (0, 11),
        "LunaticText" : "Etes-vous prêt à connaitre les idées sombre de Mathis ?",
        "Default" : (0, 11),
        "DefaultText" : "Etes-vous prêt à voir la face cachée de Mathis ?",
        "All" : (0, 11),
        "AllText" : "Etes-vous prêt à devenir Mathis ?",
    },
    "Maths" : {
        "Easy" : (12, 21),
        "EasyText" : "Connaissez-vous les basiques ?",
        "Normal" : (22, 31),
        "NormalText" : "Etes-vous prêts à retourner en CM2 ?",
        "Hard" : (32, 41),
        "HardText" : "Connaissez-vous les formules complexes ?",
        "Lunatic" : (42, 51),
        "LunaticText" : "Vous ne voulez pas appuyer sur Commencer.",
        "Default" : (22, 31),
        "DefaultText" : "Etes-vous prêts à retourner en CM2 ?",
        "All" : (12, 51),
        "AllText" : "Etes-vous prêts a découvrir la création de Chuck Norris ?",
    },
    "Geography" : {
        "Easy" : (52, 61),
        "EasyText" : "Savez-vous vous repérez ?",
        "Normal" : (62, 71),
        "NormalText" : "Le Nord n'est pas tout le temps en haut.",
        "Hard" : (72, 81),
        "HardText" : "Contrairement a ce que pense les Américains, Madagascar 2 n'est pas un pays.",
        "Lunatic" : (82, 91),
        "LunaticText" : "A tout hasard, êtes-vous perdu ?",
        "Default" : (62, 71),
        "DefaultText" : "Le Nord n'est pas tout le temps en haut.",
        "All" : (52, 91),
        "AllText" : "Tous les chemins mènent a Rome !",
    },
    "History" : {
        "Easy" : (92, 101),
        "EasyText" : "Le feu n'a pas été inventé.",
        "Normal" : (102, 111),
        "NormalText" : "C'est frustrant mais la vie n'a pas commencé en l'an 0.",
        "Hard" : (112, 121),
        "HardText" : "Vous ne pouvez pas retourner dans le futur.",
        "Lunatic" : (122, 131),
        "LunaticText" : "L'histoire commence avec un H, comme un certain autrichien.",
        "Default" : (102, 111),
        "DefaultText" : "C'est frustrant mais la vie n'a pas commencé en l'an 0.",
        "All" : (92, 131),
        "AllText" : "Vous allez vous endormir.",
    },
    "Video Games" : {
        "Easy" : (132, 141),
        "EasyText" : "Pikachu est une souris.",
        "Normal" : (142, 151),
        "NormalText" : "Terraria n'est pas un plagiat de Minecraft.",
        "Hard" : (152, 161),
        "HardText" : "Hatsune Miku est probablement plus vielle que vous.",
        "Lunatic" : (162, 171),
        "LunaticText" : "Pourquoi une barre de vie de boss viens d'apparaître ??",
        "Default" : (142, 151),
        "DefaultText" : "Terraria n'est pas un plagiat de Minecraft.",
        "All" : (132, 171),
        "AllText" : "Vous saviez que quelqu'un finira 1.6 fois Minecraft avant que vous arriviez a la fin de ce QCM ?",
    },
    "General Culture" : {
        "Easy" : (172, 181),
        "EasyText" : "La Russie n'est toujours pas un continent.",
        "Normal" : (182, 191),
        "NormalText" : "Couteaux a droite, Fourchettes a gauches.",
        "Hard" : (192, 201),
        "HardText" : "La majorité des citations d'internet sont faussement attribué. -Rick Astley.",
        "Lunatic" : (202, 211),
        "LunaticText" : "Chuck Norris vous observe.",
        "Default" : (182, 191),
        "DefaultText" : "Couteaux a droite, Fourchettes a gauches.",
        "All" : (172, 211),
        "AllText" : "Vous ne passerez pas.",
    }
}
